{% set name = "circleseeker" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # For local builds from the working tree
  path: ..
  # For Bioconda, replace the above with an sdist or GitHub tag URL and sha256, e.g.:
  # url: https://github.com/circleseeker/circleseeker2/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: <fill-in-from-release>

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - circleseeker = circleseeker.cli:main
    - CircleSeeker = circleseeker.cli:main

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=68
    - wheel
    - setuptools-scm
  run:
    - python >=3.9
    - click >=8.1
    - pandas >=2.0
    - numpy >=1.23
    - biopython >=1.81
    - pysam >=0.22
    - pyyaml >=6.0
    - networkx >=3.0
    - packaging >=23
    - intervaltree >=3.1
    # External bioinformatics tools
    - tidehunter
    - blast
    - minimap2
    - samtools
    - cd-hit
    - bcftools
    - varlociraptor
    - cyrcular

test:
  requires:
    - pip
  imports:
    - circleseeker
    - circleseeker.core
    - circleseeker.modules
    - circleseeker.external
  commands:
    - circleseeker --help
    - CircleSeeker --help
    - python -c "import circleseeker; print(circleseeker.__version__)"
    - python -c "from circleseeker.modules import ecc_summary; print('Module test passed')"
    - python -m pip check

about:
  home: https://github.com/circleseeker/circleseeker2
  license: GPL-2.0-only
  license_family: GPL
  summary: Comprehensive eccDNA detection from PacBio HiFi sequencing data
  description: |
    CircleSeeker2 is a specialized bioinformatics pipeline designed for the 
    identification, classification, and characterization of extrachromosomal 
    circular DNA (eccDNA) from PacBio HiFi long-read sequencing data.
    
    Key features:
    - Hybrid detection strategy combining tandem repeat detection with Split-Read assembly
    - Comprehensive eccDNA classification (UeccDNA, MeccDNA, CeccDNA, MCeccDNA, XeccDNA)
    - Automated pipeline with checkpoint and resumption capabilities
    - Detailed HTML reports and comprehensive output formats
    - Modular architecture with 15 processing steps
    
  doc_url: https://circleseeker2.readthedocs.io
  dev_url: https://github.com/circleseeker/circleseeker2

extra:
  recipe-maintainers:
    - leoxqy
    - yaoxinzhang
