{% set name = "circle_seeker" %}
{% set version = "1.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - numpy >=1.22
    - pandas
    - pysam
    - biopython
    - minimap2
    - samtools
    - blast
    - bedtools
    - seqkit
    - tidehunter
    - pbtk 
  run:
    - python
    - numpy >=1.22
    - pandas
    - pysam
    - biopython
    - minimap2
    - samtools
    - blast
    - bedtools
    - seqkit
    - tidehunter
    - pbtk

# Commented out test section
# test:
#   imports:
#     - circle_seeker
#   commands:
#     - CircleSeeker --help
#     - CircleSeeker -i DNA_2k.fasta -o test_output -r ref_db.fa -n 16

about:
  home: "https://github.com/leoxqy/CircleSeeker"
  license: "GPL-2.0"
  license_family: "GPL"
  summary: "Circle-Seeker: A specialized bioinformatics tool for circular DNA analysis."
  description: |
    This comprehensive software processes high-throughput long-read sequences to efficiently identify and characterize various types of extrachromosomal circular DNA (eccDNA) structures, leveraging the high accuracy and long read lengths of PacBio HiFi technology.

extra:
  recipe-maintainers:
    - leoxqy
    - YxZhang-XHCY

